server:
  port: 9999
spring:
  application:
    name: server-oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC
    username: root
    password: 123456